export default [
  // UI
  'TOGGLE_SIDE_BAR',

  // API
  'LOGIN',
  'REGISTER',
  'GET_USERS',
  'DELETE_USER',

  'INSERT_TEST',
  'GET_TESTS_BY_TEACHER',
  'GET_TEST_BY_ID',
  'UPDATE_TEST',
  'DELETE_TEST',
  'GET_TESTS_WAITING_ADMIN',
  'CHANGE_STATUS_TEST_DRAFT',
  'CHANGE_STATUS_TEST_DONE',
  'GET_TESTS_DONE',

  'GET_STUDENTS',
  

  'INSERT_EXAM',
  'GET_EXAMS_BY_TEACHER',
  'GET_EXAM_BY_ID',
  'GET_EXAMS_BY_STUDENT',
  'GET_ROOMS_EXAM',
  'GET_STUDENTS_IN_EXAM',

  // Store
  'CLEAR_STORE'
]
